apiVersion: v1
kind: Pod
metadata:
  namespace: employeehq
  name: {{ serviceName }}-mongodb
  labels:
    app: {{ serviceName }}-mongodb
spec:
  volumes:
  - name: {{ serviceName }}-mongo-vol
    persistentVolumeClaim:
      claimName: employeehq-volume-claim
  containers:
  - image: mongo
    name: employeehq-mongo-{{ serviceName }}
    command:
    - mongod
    - "--bind_ip"
    - "0.0.0.0"
    ports:
    - containerPort: 27017
    volumeMounts:
    - name: {{ serviceName }}-mongo-vol
      mountPath: /data/db
      subPath: {{ serviceName }}
