apiVersion: v1
kind: Service
metadata:
  namespace: employeehq
  labels:
    app: {{ serviceName }}-mongodb
  name: {{ serviceName }}-mongo-service
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: {{ serviceName }}-mongodb
